apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: olymahmudmugdho/product-service:a3bc99932534a65612a571918551e4a379e41f95
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
