apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: olymahmudmugdho/product-service:dcad2de734a7001069c0e4195e2b6c8a00408a43
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
