apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: olymahmudmugdho/product-service:e972edf53be33d035a277bc8ce0d321c00aa26ee
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
