apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
    spec:
      containers:
        - name: ecommerce-ui
          image: olymahmudmugdho/cne-ecommerce-ui:4bdd71c01e8b16c11ba1c6de16d9e025b0d7a4c2
          ports:
            - containerPort: 4173
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
