apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui-service
  namespace: cloud-native-ecommerce
spec:
  selector:
    app: ecommerce-ui
  ports:
    - port: 80
      targetPort: 4173
  type: LoadBalancer
    
