apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-service
  namespace: cloud-native-ecommerce
spec:
  selector:
    app: cloud-gateway-service
  ports:
    - port: 80
      targetPort: 8080
