apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: cloud-native-ecommerce
spec:
  selector:
    app: inventory-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
    
